### ISSUE TITLE
Set track styles

### ISSUE THREAD

**Issue by faroit** [naomiaro/waveform-playlist#28]
I would propose to add custom style element to the playlist tracks and also allow tracks to have unique identifiers and a class attribute which would enable to set the styles later.

something like:

```
{
  //a media path for XHR or a File object.
  "src": "media/audio/BassDrums30.mp3",

  //name that will display in the playlist control panel.
  "name": "Drums",

  // set id for track
  "id": "drums",
}
```

that way, one could add a custom css like this

```css
 .playlist .controls #drums header{
      background-color: red;
}
```
